destination: public
title: John Ngo
meta:
  title: Hi, Iâ€™m John Ngo
  description: Delivering exceptional customer experiences through empowering people, establishing processes, and shaping products.
  url: http://smallepic.com/
exclude: ['README.md']
include: ['.well-known']
